source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'


# ignoring warning from pods
inhibit_all_warnings!


def pods
pod 'GPUImage', '0.1.7'

end

target 'ACGPUImageFilters' do
    pods
end
